config/routes.rb
RailsBase::Application.routes.draw do
  #devise_for :admins

  #authenticate :admin do
  #  namespace :admins do
  #    match '/' => 'admin#index'
  #    resources :banners
  #    resources :brands
  #    resources :campaigns
  #    resources :experts
  #    resources :pages
  #    resources :plans
  #    resources :services
  #    resources :testimonials
  #  end
  #end
  #match '/ui(/:action)', controller: :ui

  #match '/test' => redirect {|ps,request| 'http://asdf.com/?' + ps.to_query }

# Handle all flexible sections with these 2 routes
  match '/*controller(/:action)'
  match '/*controller/:action'

# EXPERIMENTS
  # exp: nested controller route test
  # see: '/*controller/:action'

  # exp: route param catching slashes
  get '/get-slashes((/*experiment)/:act)' => 'pages#route_params', as: :route_exp
  # WORKS!  # get '/route(/*experiment)' => 'pages#route_params', as: :route_exp
  # WORKS!  # get '/route(/:experiment)' => 'pages#route_params', as: :route_exp, constraints: { experiment: /.*/ }

  # exp: .net style enum for rails
  get '/ruby-enum' => 'pseudo_enumerable#index', as: :pseudo_enumerable_test

  # exp: basic auth
  get '/basic-auth' => 'basic_auth#index', as: :basic_auth
  get '/basic-auth/private' => 'basic_auth#private', as: :basic_auth_private

# REFACTORING PATTERNS
  get '/refactor/:name' => 'refactor#show', as: :show_refactor
  root :to => 'blog#index'
end

app/models/pseudo_enum.rb
class PseudoEnum
  attr_accessor :string_status
  # private attribute :enum_status

#----------------------------------- <strong>
# Self-Encapsulating Field (get/set)
#-----------------------------------

  def enum_status
    statuses[@enum_status]
  end

  def enum_status= status
    return @enum_status = statuses.invert.fetch(status) if status.is_a?(String)
    @enum_status = status
  end

  # REFERENCE HASH
  #---------------
  def statuses
    {
      1 => 'Active',
      2 => 'Cancelled',
      3 => 'Other',
    }
  end
#</strong>-----------------------------------


# For Experimental Conditionals
#------------------------------

  def self.enum_status_by_id(id)
    statuses(id)
  end

  def enum_status_id
    instance_variable_get :@enum_status
  end

  # <strong> Conditional Testing Methods
  # ----------------------------
  def active?
    enum_status_id == 1
  end

  def cancelled?
    enum_status_id == 2
  end # </strong>

  # <strong> Set status without magic numbers throughout the code ( ps_enum.status = PseudoEnum.active )
  # --------------------------------------------------------------------------------------------
  def self.active
    1
  end

  def self.cancelled
    2
  end # </strong>

end

app/models/pseudo_enum_status.rb
class PseudoEnumStatus
  def self.ACTIVE
    1
  end
end

app/models/refactor.rb
require 'haml'

class Refactor
  def self.pattern_name(v=nil)
    return @name if v.nil?
    @name = v
  end
  def self.steps(v=nil)
    return @steps.map.with_index{|s,i|
      {
        name: s.name,
        description: s.description,
        filenames: s.filenames(i)
      }
    } if v.nil?
    @steps = v
  end
  def self.motivation(v=nil)
    return @motivation if v.nil?
    @motivation = Haml::Engine.new(v).render
  end

  class Step
    attr_accessor :name, :description
    def initialize(args)
      args.each{|k,v| instance_variable_set "@#{k}".to_sym, v }
    end

    def refactor_name
      @refactor.to_s.split('::').last
    end

    def step_no(i)
      sprintf('%.3d', i)
    end

    def filename(i,ab=:a)
      "./app/models/refactor/#{refactor_name.underscore}/step_#{step_no(i)}_#{ab}.rb"
    end

    def filenames(i)
      [
        filename(i),   # "./app/models/refactor/#{refactor_name.underscore}/step_#{step_no(i)}_a.rb",
        filename(i,:b) # "./app/models/refactor/#{refactor_name.underscore}/step_#{step_no(i)}_b.rb"
      ]
    end
  end
end

app/models/refactor/self_encapsulate_field.rb
class Refactor::SelfEncapsulateField < Refactor
  pattern_name 'self_encapsulate_field'

  steps [
          Refactor::Step.new(refactor: self, name: 'Starting Point', description: 'Use sets/gets to prevent direct access to an attribute.'),
          Refactor::Step.new(refactor: self, name: 'Create Sets/Gets', description: 'Define sets/gets.'),
          Refactor::Step.new(refactor: self, name: 'Make attribute private', description: 'Prevent direct access to attribute.'),
        ]

  motivation <<-MOTIVATION
%p
  :escaped
    Enforcing indirect access to attributes on a class via sets/gets.

    Combine this pattern with other patterns including:
%ul
  %li Replace Type Code with State/Strategy
  %li Replace Conditional with Polymorphism
  MOTIVATION
end

app/models/refactor/self_encapsulate_field/step_000_a.rb
class Refactor::SelfEncapsulateField::Step000A

end

app/models/refactor/self_encapsulate_field/step_000_b.rb
class Refactor::SelfEncapsulateField::Step000B

end

app/controllers/a/b/c/act_controller.rb
class A::B::C::ActController < ApplicationController

end

app/controllers/a/b/c_controller.rb
class A::B::CController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  expose(:refactoring_patterns) {
    Dir.glob('./app/models/refactor/*/').map do |file|
      file.split('/').last
    end
  }
end

app/controllers/basic_auth_controller.rb
class BasicAuthController < ApplicationController

  http_basic_authenticate_with name: 'guest',
                               password: 'guest',
                               only: :private

end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  expose(:posts) { BlogSection.new('blog/posts').files.reverse }

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/pseudo_enumerable_controller.rb
class PseudoEnumerableController < ApplicationController
end

app/controllers/refactor_controller.rb
class RefactorController < ApplicationController
  expose(:name) { params[:name] }
  expose(:klass) { "refactor/#{name}".classify.constantize }
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController

  http_basic_authenticate_with :name => ENV['HTTP_USER'],
                               :password => ENV['HTTP_PASS']

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/a/b/c/act.haml
a/b/c#act

app/views/a/b/c/act/index.haml
act#index

app/views/a/b/c/act/josh.haml
act#josh

app/views/a/b/c/index.haml
.alert.alert-success You made it!

%h1 Nested Controller Route Test
%hr

%h3 Why This is Awesome
%p
  The fact that this was successful, makes this test awesome.

%p
  It has a lot of implications.  Specifically, how I can
  %ul
    %li setup 2 routes per &quot;section&quot; (A list of sections: experiments, refactoring patterns)
    %li
      %b UPDATE: setup 2 routes for all automated sections
      %p (i think it has to be this way...this route should be after all specific routes)
    %li
      %b UPDATE: (might not need to be after everything)
    %li drive each section completely (almost) thru views
    %li
      if a subsection's controller requires code:
      %ul
        %li make a nested controller containing only related code
        %li no need to update routes

%hr
%h3 Issues
%ul
  %li
    The only issue I see, is if you have a custom
    route, and it is below the following 2 routes.
    It will try to apply the last "/*" to an action
    on the controller.  If the action doesn't exist
    you get an Unknown Action exception.
  %li
    Ideally, these routes go near the bottom of your file.

%hr
%h3 The Code
%hr
%h4 Routes
.inline
  %em config/routes.rb
  %strong v1
  %pre
    :escaped
      # exp: nested controller route test

      get '/routes/*controller(/:action)'
      get '/routes/*controller/:action'
  %p The problem is, the 1st route's function isn't obvious.

.inline
  %em config/routes.rb
  %strong v2
  %pre
    :escaped
      # exp: nested controller route test

      get '/routes/*controller', action: :index
      get '/routes/*controller/:action'
  %p The 1st route tells you, I'm assuming the action is index, everything else is the controller.

%hr

%h4 Controller
%em app/controllers/a/b/c_controller.rb
%pre= IO.read('./app/controllers/a/b/c_controller.rb')

%hr

%h4 View
%em app/views/a/b/c/index.haml
%pre You made it!

app/views/basic_auth/index.haml
%h1 Experiment: Basic Auth (Rails 3.x)
%hr


%ul
  %li
    = link_to 'View Private Page', basic_auth_private_path
    %ul
      %li Username: guest
      %li Password: guest

app/views/basic_auth/private.haml
.alert.alert-info
  You should not be able to see this page
  %strong unless
  you have filled out a basic_auth user/pass.

%h1 Experiment: Basic Auth (Rails 3.x)
%hr

%h3 Private Page
%p You entered in the correct username and password.

app/views/blog/index.haml
%h1 Posts

%ul
  - posts.each do |post|
    %li= link_to *post.link

app/views/blog/posts/0000-shell_essentials_pt_1_apropos_amp_man.haml
%header.entry-header
  %h1.entry-title
    %a{:href => "http://unixsuperhero.com/2012/10/04/shell-essentials-pt-1-apropos-man/", :rel => "bookmark"} Shell Essentials, Pt. 1 – apropos &amp;&nbsp;man
  .comments-link
    %a{:href => "http://unixsuperhero.com/2012/10/04/shell-essentials-pt-1-apropos-man/#respond", :title => "Comment on Shell Essentials, Pt. 1 – apropos &amp;&nbsp;man"}
      %span.leave-reply Leave a reply
  / .comments-link
/ .entry-header
.entry-content
  %p It seems that I am always teaching someone something about the command line. It also appears to be happening more and more frequently. While the advice is most commonly about using bash, most of this advice is independent of the shell used.
  %p
    I believe that great systems are systems with a foundation composed of small, complimentary parts. When combined, these parts can form large, solid, dependable systems. Unix is a system like this. It even has a 3-point philosophy,
    = succeed "." do
      %a{:href => "http://en.wikipedia.org/wiki/Unix_philosophy", :target => "_blank", :title => "The Unix Philosophy"} The Unix Philosophy
  %p
    I believe that teaching you to use these 2 commands and use them together, you will have the strongest foundation possible. As well as, the ability and the confidence to use
    %strong any
    Unix command available to you.
  %p The 2 commands I am referring to are:
  %ol
    %li
      %code apropos
    %li
      %code man
  %p
    The first command,
    = succeed "," do
      %code apropos
    will help you determine which command to use in a given situation. For example, let’s pretend you just downloaded a .zip file, but you don’t know if there is a command that will uncompress it. Try the following command:
  %pre{:style => "padding-left:30px;"}
    %code apropos zip
  %p In the output, you might see the line:
  %pre{:style => "padding-left:30px;"}
    %code unzip(1) - list, test and extract compressed files in a ZIP archive
  %p
    Now that we have found
    = succeed "," do
      %code unzip
    the command that we were looking for, we can use the second command to learn how it is used.
  %p
    That second command,
    = succeed "," do
      %code man
    will describe
    %code unzip
    and the different possible ways to use it.
    %code man
    is an abbreviation for manual. These manuals are called man pages. Try the following command, it will open the
    %code unzip
    man page:
  %pre
    %code man unzip
  %p
    While reading the
    %code unzip
    man page, press “h”. This will show you the many keystrokes used to navigate the manual, or close it by pressing “q”.
  %p Now that you know these commands, use them shamelessly as you master the Unix command line.
  %p Here are a few man pages to skim over. It won’t hurt you to practice the commands you just learned:
  %pre{:style => "padding-left:30px;"}
    %code
      :preserve
        man man # that's right, the manual for man
        man bash
        man ls  #jp-post-flair.sharedaddy.sd-like-enabled.sd-sharing-enabled
/ .entry-content
%footer.entry-meta
  This entry was posted in
  %a{:href => "http://unixsuperhero.com/category/uncategorized/", :rel => "category tag", :title => "View all posts in Uncategorized"} Uncategorized
  and tagged
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/apropos/", :rel => "tag"} apropos
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/bash/", :rel => "tag"} Bash
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/bash-lesson/", :rel => "tag"} bash lesson
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/bash-tips/", :rel => "tag"} bash tips
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/bash-tutorial/", :rel => "tag"} bash tutorial
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/man/", :rel => "tag"} man
  %a{:href => "http://unixsuperhero.com/tag/manpages/", :rel => "tag"} manpages
  on
  %a{:href => "http://unixsuperhero.com/2012/10/04/shell-essentials-pt-1-apropos-man/", :rel => "bookmark", :title => "5:47 pm"}
    %time.entry-date{:datetime => "2012-10-04T17:47:50+00:00"} October 4, 2012
  = succeed "." do
    %span.by-author
      by
      %span.author.vcard
        %a.url.fn.n{:href => "http://unixsuperhero.com/author/unixsuperhero/", :rel => "author", :title => "View all posts by unixsuperhero"} unixsuperhero
  %span.edit-link
    %a.post-edit-link{:href => "http://unixsuperhero.wordpress.com/wp-admin/post.php?post=4&amp;action=edit", :title => "Edit Post"} Edit
/ .entry-meta

app/views/blog/posts/0003-private_preface_craftsmanship.haml
%header.entry-header
  %h1.entry-title
    %a{:href => "http://unixsuperhero.com/2012/10/04/preface-craftsmanship/", :rel => "bookmark"} Private: Preface:&nbsp;Craftsmanship
  .comments-link
    %a{:href => "http://unixsuperhero.com/2012/10/04/preface-craftsmanship/#respond", :title => "Comment on Private: Preface:&nbsp;Craftsmanship"}
      %span.leave-reply Leave a reply
  / .comments-link
/ .entry-header
.entry-content
  %h3{:style => "text-align:center;"} Preface
  %p First of all, I would like to make note of why this post is labeled: “Preface”. &nbsp;In Book Design, the Preface is a part of “Front matter”. &nbsp;It often tells a story about the book, setting the tone. &nbsp;That being said, I hope there are other developers out there who strive to be masters of their craft, and these logs help along the way.
  %p Master Craftsman: A Developer’s Aspiration
  %p
    [ Intro ]
    %br/
    Programming is my craft. The same way carpentry is for wood
    %br/
    workers. I eat, sleep, and breathe software. When I see
    %br/
    software someone else made, I wonder how it works. I
    %br/
    critique it. Whether it is your own work, or someone else’s,
    %br/
    I believe these two actions are what make a good craftsman.
  %p
    [ Tools ]
    %br/
    Craftsmen use tools. It is important to know your tools.
    %br/
    Which tasks a tool is best suited for. When to use a tool,
    %br/
    and when not to. Someone who is truely skilled, uses their
    %br/
    tools as an extention of themselves. Like a samurai and his
    %br/
    sword.
    %br/
    The main tools that I use are:
    %br/
    \- unix shell
    %br/
    \- vim
    %br/
    \- a web browser
    %br/
    For years I have studied bash and vim, all while using a web
    %br/
    browser. Countless hours have been spent reading man pages
    %br/
    and the vim help docs, and rewriting the information in my own
    %br/
    words. These are two of the most powerful resources available
    %br/
    to you. Unlike the internet, these resources are usually free
    %br/
    from the public’s opinion. However, of course, the internet
    %br/
    is still another powerful source of information.
  %p
    [ Humility ]
    %br/
    It is important to accept when you are wrong. Understanding
    %br/
    why and learning from the experience is one of the quickest
    %br/
    ways to learn. The feeling of humiliation has a profound
    %br/
    effect on what information stands out in your memory. It may
    %br/
    sting at first, but the quicker you can get past it, the
    %br/
    better off you will be.
  %p
    [ Practice ]
    %br/
    A master is someone who never stops practicing. Everything
    %br/
    produced provides another learning experience. The subtle
    %br/
    difference in the angle of a blade, and the effect it had on a
    %br/
    block on wood. Aspect that seem insignificant, like the
    %br/
    amount of pressure applied when kneading dough, are all
    %br/
    variables that can affect the outcome.
  %p
    [ Trying different things ]
    %br/
    What goes hand-in-hand with practice, is trying new things.
    %br/
    Not being afraid to try something new, is an important
    %br/
    quality. If it fails, chances are, you won’t die. Whether it
    %br/
    fails or succeeds, I’m sure you will have learned something
    %br/
    new. Be it, something never to do again, a great technique
    %br/
    that works, or maybe it leads to more questions and more
    %br/
    things to try. Everything contributes to your success.
  %p
    [ trash ]
    %br/
    Craftwork is something you do by hand, as a human. We are
    %br/
    collections of information. It is important to understand
    %br/
    that other programmers know things that you do not. To
    %br/
    meet another developer is an opportunity to ask him/her
    %br/
    questions, and pick her brain.
  %h3 Master Craftsman: A Developer’s Aspiration
  %p
    %strong Outline
  %ul
    %li Know your tools, and know them well. so much, that you can use them in unconventional ways. (eg. A chef and ingredients.)
    %li Keep useful parts, ignore/forget useless parts. This might lead you to think, forget everything that doesn’t work. But, some broken things are worth remembering. Which is why some people document anti-patterns. It helps to avoid methods that are known to break or lead to dead-ends. (Usefulness doesn’t necessarily mean good. Some bugs and issues are useful to remember.) (this may be an obvious point, aka useless, so discard it)
    %li Know your own habits and limitations. (Muscle memory, maybe.) By knowing what you are prone to do, you can change your workflow to accomodate habits and leverage them.
    %li One who is not afraid to be wrong. &nbsp;Basically, everyone makes mistakes or poor design decisions. &nbsp;Those who understand this, and take constructive criticism well, are more likely to grow. &nbsp;I’m always looking for a better way. &nbsp;If I see someone do something I haven’t seen before; or something cooler/faster than the way I would do it, I’m quick to ask how or why.
    %li using your time wisely. Don’t get stuck on newb issues. I had a better idea of what this meant earlier.
    %li practice. For me, this (vaguely) goes hand-in-hand with fear of failure. If I can avoid it, I don’t like to look bad in front of people. That sounds worse than it is. Rather, if I can help it, I like to appear skilled in front if people. And this has always driven me to practice in my own time. I was trying to think of how we could practice programming. Because, it’s not fun to practice drilling, nor practical, coming up with all sorts of ideas. Then I realized that debugging is practice. A very good form of practice. It helps concepts stick because you figure them out for yourself.
  #jp-post-flair.sharedaddy.sd-like-enabled.sd-sharing-enabled
/ .entry-content
%footer.entry-meta
  This entry was posted in
  %a{:href => "http://unixsuperhero.com/category/uncategorized/", :rel => "category tag", :title => "View all posts in Uncategorized"} Uncategorized
  on
  %a{:href => "http://unixsuperhero.com/2012/10/04/preface-craftsmanship/", :rel => "bookmark", :title => "5:54 pm"}
    %time.entry-date{:datetime => "2012-10-04T17:54:49+00:00"} October 4, 2012
  = succeed "." do
    %span.by-author
      by
      %span.author.vcard
        %a.url.fn.n{:href => "http://unixsuperhero.com/author/unixsuperhero/", :rel => "author", :title => "View all posts by unixsuperhero"} unixsuperhero
  %span.edit-link
    %a.post-edit-link{:href => "http://unixsuperhero.wordpress.com/wp-admin/post.php?post=11&amp;action=edit", :title => "Edit Post"} Edit
/ .entry-meta

app/views/blog/posts/0008-fix_gcc_and_segfault_issues_with_newer_versions_of_ruby_on_lion.haml
%header.entry-header
  %h1.entry-title
    %a{:href => "http://unixsuperhero.com/2012/10/10/fix-gcc-and-segfault-issues-with-newer-versions-of-ruby-on-lion/", :rel => "bookmark"} fix gcc and segfault issues with newer versions of ruby on&nbsp;lion
  .comments-link
    %a{:href => "http://unixsuperhero.com/2012/10/10/fix-gcc-and-segfault-issues-with-newer-versions-of-ruby-on-lion/#respond", :title => "Comment on fix gcc and segfault issues with newer versions of ruby on&nbsp;lion"}
      %span.leave-reply Leave a reply
  / .comments-link
/ .entry-header
.entry-content
  %p
    I have had a lot of issues after I upgraded to OS X Lion.  Mostly because of a common XCode issue.  Then I got it to work temporarily with a specific package apple released that is just the cli tools for osx.  Then I had some luck with an llvm version of gcc.  Not one of these solutions was perfect.  I was reading the
    %a{:href => "https://github.com/kennethreitz/osx-gcc-installer"} osx-gcc-installer
    README.  I saw that if you had Homebrew, you could install apple-gcc42:
  %pre
    :preserve
      # pull in the repo with apple-gcc42 (homebrew/dupes aka github.com/Homebrew/homebrew-dupes)
      brew tap homebrew/dupes
      brew install apple-gcc42  %p This didn’t work for me.  Because you can’t compare a flow to a symbol (:lion).  So, I changed the symbol to “10.7″, no quotes.  Tried brew install again.  It worked.  Then I just reinstalled my ruby, gems, and everything has been fine since.  Yes, this was rushed.  Here are the commands I ran, thanks to reading “rvm requirements”.
  %pre
    :preserve
      rvm requirements
      brew install libksba #not sure if this is necessary
      vim /usr/local/Library/Formula/apple-gcc42.rb # :%s/:lion/10.7/c
      brew install apple-gcc42
      rvm install 1.9.3  #jp-post-flair.sharedaddy.sd-like-enabled.sd-sharing-enabled
/ .entry-content
%footer.entry-meta
  This entry was posted in
  %a{:href => "http://unixsuperhero.com/category/uncategorized/", :rel => "category tag", :title => "View all posts in Uncategorized"} Uncategorized
  and tagged
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/1-9-3/", :rel => "tag"} 1.9.3
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/bugfix/", :rel => "tag"} bugfix
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/compile-error/", :rel => "tag"} compile error
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/gc/", :rel => "tag"} gc
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/gcc/", :rel => "tag"} gcc
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/homebrew/", :rel => "tag"} homebrew
  %a{:href => "http://unixsuperhero.com/tag/ruby/", :rel => "tag"} ruby
  on
  %a{:href => "http://unixsuperhero.com/2012/10/10/fix-gcc-and-segfault-issues-with-newer-versions-of-ruby-on-lion/", :rel => "bookmark", :title => "4:03 pm"}
    %time.entry-date{:datetime => "2012-10-10T16:03:38+00:00"} October 10, 2012
  = succeed "." do
    %span.by-author
      by
      %span.author.vcard
        %a.url.fn.n{:href => "http://unixsuperhero.com/author/unixsuperhero/", :rel => "author", :title => "View all posts by unixsuperhero"} unixsuperhero
  %span.edit-link
    %a.post-edit-link{:href => "http://unixsuperhero.wordpress.com/wp-admin/post.php?post=47&amp;action=edit", :title => "Edit Post"} Edit
/ .entry-meta

app/views/blog/posts/0019-home_row_tip_2_without_leaving_the_home_row_scroll_up_down_a_webpage.haml
%header.entry-header
  %h1.entry-title
    %a{:href => "http://unixsuperhero.com/2013/01/14/home-row-tip-2-without-leaving-the-home-row-scroll-updown-a-webpage/", :rel => "bookmark"} Home Row Tip #2: Without Leaving the Home Row, Scroll Up/Down a&nbsp;Webpage
  .comments-link
    %a{:href => "http://unixsuperhero.com/2013/01/14/home-row-tip-2-without-leaving-the-home-row-scroll-updown-a-webpage/#respond", :title => "Comment on Home Row Tip #2: Without Leaving the Home Row, Scroll Up/Down a&nbsp;Webpage"}
      %span.leave-reply Leave a reply
  / .comments-link
/ .entry-header
.entry-content
  %h3 The Home Row is Good.  Your Mouse is Evil.
  %p
    To scroll down: &nbsp;
    %strong> Spacebar
    \.
  %p
    To scroll up:
    %strong Shift
    = succeed "&amp;nbsp;" do
      %strong +
    %strong Spacebar
    %strong .
  #jp-post-flair.sharedaddy.sd-like-enabled.sd-sharing-enabled
/ .entry-content
%footer.entry-meta
  This entry was posted in
  %a{:href => "http://unixsuperhero.com/category/uncategorized/", :rel => "category tag", :title => "View all posts in Uncategorized"} Uncategorized
  and tagged
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/home-row/", :rel => "tag"} home row
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/homerow/", :rel => "tag"} homerow
  = succeed "," do
    %a{:href => "http://unixsuperhero.com/tag/keyboard-shortcuts/", :rel => "tag"} keyboard shortcuts
  %a{:href => "http://unixsuperhero.com/tag/no-mouse/", :rel => "tag"} no mouse
  on
  %a{:href => "http://unixsuperhero.com/2013/01/14/home-row-tip-2-without-leaving-the-home-row-scroll-updown-a-webpage/", :rel => "bookmark", :title => "2:37 am"}
    %time.entry-date{:datetime => "2013-01-14T02:37:35+00:00"} January 14, 2013
  = succeed "." do
    %span.by-author
      by
      %span.author.vcard
        %a.url.fn.n{:href => "http://unixsuperhero.com/author/unixsuperhero/", :rel => "author", :title => "View all posts by unixsuperhero"} unixsuperhero
  %span.edit-link
    %a.post-edit-link{:href => "http://unixsuperhero.wordpress.com/wp-admin/post.php?post=136&amp;action=edit", :title => "Edit Post"} Edit
/ .entry-meta

app/views/blog/posts/0038-dynamically_download_something_with_javascript.haml
%h1 Javascript to create/download a file dynamically...

.alert.alert-info
  I think this only works in chrome. (This should be a blue box.)

%pre
  :escaped
    function dynamic_download(data, name) {
      var content = new Blob([data], {type:'text/plain'});

      var temp_link = document.createElement("a");
      temp_link.href = window.webkitURL.createObjectURL(content);
      temp_link.download = name;
      temp_link.click();
    }

%h4 Source
= link_to "somebody's site", 'http://thiscouldbebetter.wordpress.com/2012/12/18/loading-editing-and-saving-a-text-file-in-html5-using-javascrip/'

app/views/todo/refactor_tdsm.haml
%h1 Refactor / Redesign TDSM
%hr

Files
%ul
  %li lib/tdsm.rb
  %li lib/tdsm/*