config/routes.rb
RailsBase::Application.routes.draw do
  #devise_for :admins

  #authenticate :admin do
  #  namespace :admins do
  #    match '/' => 'admin#index'
  #    resources :banners
  #    resources :brands
  #    resources :campaigns
  #    resources :experts
  #    resources :pages
  #    resources :plans
  #    resources :services
  #    resources :testimonials
  #  end
  #end
  #match '/ui(/:action)', controller: :ui

  #match '/test' => redirect {|ps,request| 'http://asdf.com/?' + ps.to_query }

# Handle all flexible sections with these 2 routes
  match '/*controller(/:action)'
  match '/*controller/:action'

# EXPERIMENTS
  # exp: nested controller route test
  # see: '/*controller/:action'

  # exp: route param catching slashes
  get '/get-slashes((/*experiment)/:act)' => 'pages#route_params', as: :route_exp
  # WORKS!  # get '/route(/*experiment)' => 'pages#route_params', as: :route_exp
  # WORKS!  # get '/route(/:experiment)' => 'pages#route_params', as: :route_exp, constraints: { experiment: /.*/ }

  # exp: .net style enum for rails
  get '/ruby-enum' => 'pseudo_enumerable#index', as: :pseudo_enumerable_test

  # exp: basic auth
  get '/basic-auth' => 'basic_auth#index', as: :basic_auth
  get '/basic-auth/private' => 'basic_auth#private', as: :basic_auth_private

# REFACTORING PATTERNS
  get '/refactor/:name' => 'refactor#show', as: :show_refactor
  root :to => 'blog#index'
end

app/models/pseudo_enum.rb
class PseudoEnum
  attr_accessor :string_status
  # private attribute :enum_status

#----------------------------------- <strong>
# Self-Encapsulating Field (get/set)
#-----------------------------------

  def enum_status
    statuses[@enum_status]
  end

  def enum_status= status
    return @enum_status = statuses.invert.fetch(status) if status.is_a?(String)
    @enum_status = status
  end

  # REFERENCE HASH
  #---------------
  def statuses
    {
      1 => 'Active',
      2 => 'Cancelled',
      3 => 'Other',
    }
  end
#</strong>-----------------------------------


# For Experimental Conditionals
#------------------------------

  def self.enum_status_by_id(id)
    statuses(id)
  end

  def enum_status_id
    instance_variable_get :@enum_status
  end

  # <strong> Conditional Testing Methods
  # ----------------------------
  def active?
    enum_status_id == 1
  end

  def cancelled?
    enum_status_id == 2
  end # </strong>

  # <strong> Set status without magic numbers throughout the code ( ps_enum.status = PseudoEnum.active )
  # --------------------------------------------------------------------------------------------
  def self.active
    1
  end

  def self.cancelled
    2
  end # </strong>

end

app/models/pseudo_enum_status.rb
class PseudoEnumStatus
  def self.ACTIVE
    1
  end
end

app/models/refactor.rb
require 'haml'

class Refactor
  def self.pattern_name(v=nil)
    return @name if v.nil?
    @name = v
  end
  def self.steps(v=nil)
    return @steps.map.with_index{|s,i|
      {
        name: s.name,
        description: s.description,
        filenames: s.filenames(i)
      }
    } if v.nil?
    @steps = v
  end
  def self.motivation(v=nil)
    return @motivation if v.nil?
    @motivation = Haml::Engine.new(v).render
  end

  class Step
    attr_accessor :name, :description
    def initialize(args)
      args.each{|k,v| instance_variable_set "@#{k}".to_sym, v }
    end

    def refactor_name
      @refactor.to_s.split('::').last
    end

    def step_no(i)
      sprintf('%.3d', i)
    end

    def filename(i,ab=:a)
      "./app/models/refactor/#{refactor_name.underscore}/step_#{step_no(i)}_#{ab}.rb"
    end

    def filenames(i)
      [
        filename(i),   # "./app/models/refactor/#{refactor_name.underscore}/step_#{step_no(i)}_a.rb",
        filename(i,:b) # "./app/models/refactor/#{refactor_name.underscore}/step_#{step_no(i)}_b.rb"
      ]
    end
  end
end

app/models/refactor/self_encapsulate_field.rb
class Refactor::SelfEncapsulateField < Refactor
  pattern_name 'self_encapsulate_field'

  steps [
          Refactor::Step.new(refactor: self, name: 'Starting Point', description: 'Use sets/gets to prevent direct access to an attribute.'),
          Refactor::Step.new(refactor: self, name: 'Create Sets/Gets', description: 'Define sets/gets.'),
          Refactor::Step.new(refactor: self, name: 'Make attribute private', description: 'Prevent direct access to attribute.'),
        ]

  motivation <<-MOTIVATION
%p
  :escaped
    Enforcing indirect access to attributes on a class via sets/gets.

    Combine this pattern with other patterns including:
%ul
  %li Replace Type Code with State/Strategy
  %li Replace Conditional with Polymorphism
  MOTIVATION
end

app/models/refactor/self_encapsulate_field/step_000_a.rb
class Refactor::SelfEncapsulateField::Step000A

end

app/models/refactor/self_encapsulate_field/step_000_b.rb
class Refactor::SelfEncapsulateField::Step000B

end

app/controllers/a/b/c_controller.rb
class A::B::CController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  expose(:refactoring_patterns) {
    Dir.glob('./app/models/refactor/*/').map do |file|
      file.split('/').last
    end
  }
end

app/controllers/basic_auth_controller.rb
class BasicAuthController < ApplicationController

  http_basic_authenticate_with name: 'guest',
                               password: 'guest',
                               only: :private

end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  expose(:posts) { BlogSection.new('blog/posts').files.reverse }

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/pseudo_enumerable_controller.rb
class PseudoEnumerableController < ApplicationController
end

app/controllers/refactor_controller.rb
class RefactorController < ApplicationController
  expose(:name) { params[:name] }
  expose(:klass) { "refactor/#{name}".classify.constantize }
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController

  http_basic_authenticate_with :name => ENV['HTTP_USER'],
                               :password => ENV['HTTP_PASS']

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    - if content_for?(:title)
      %title= yield(:title)
    - else
      %title Default Title

    = csrf_meta_tags

    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = favicon_link_tag "favicon.png"
%body
  .row-fluid
    .span10.header
      .pre
        %h1 Unix Superhero
        %p Blog, code experiments, notes, etc.
    .span2.header
      .pre
        %h2 Site Code
        %p= link_to 'github:rails-experiments', 'http://github.com/unixsuperhero/rails-experiments', target: '_blank'
  .row-fluid
    .span2.navigation
      .pre
        .h1 Navigation
        %hr.separate
        = link_to 'Home', '/'
        = link_to 'Todo', '/todo'
        %hr.separate
        .h2 Experiments
        %hr
        = link_to 'Basic Auth (Rails 3.x)', basic_auth_path
        = link_to '.NET Enum in Ruby?', pseudo_enumerable_test_path
        = link_to 'Route Tests', route_exp_path
        = link_to 'Nested Controller Routes', '/a/b/c'
        = link_to 'Nested Controller Routes 2', '/a/b/c/act'
        %hr.separate
        .h2 Refactoring Patterns
        %hr
        - refactoring_patterns.each do |pattern|
          = link_to pattern.titleize, show_refactor_path(pattern)
    .span10.page
      .clearfix
      - flash.each do |k,v|
        %p(class=k)= v
      = yield

app/views/pages/index.haml
Blog Coming Soon...

app/views/pages/route_params.haml
%pre
  :escaped
    params[:experiment]: #{params[:experiment].inspect}
    params[:act]: #{params[:act].inspect}

%p
  Test links:
  %ul
    %li= link_to "/get-slashes", route_exp_path
    - paths = %w{ one one/two one/two/three }
    - paths.each do |pth|
      %li= link_to "/get-slashes/#{pth}", "/get-slashes/#{pth}"